name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Client
        run: |
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/client:latest ./client
          # Increment version tag
          # Example: Get the latest tag, increment it, and use it
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          # Increment tag
          NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$NF++;print}' OFS=.)
          docker tag ${{ secrets.DOCKER_USERNAME }}/client:latest ${{ secrets.DOCKER_USERNAME }}/client:$NEW_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/client:$NEW_TAG

      - name: Build Image 2
        run: docker build -t sakosa878/auth ./auth

      - name: Build Image 3
        run: docker build -t sakosa878/msg ./message

      # Log in to Docker Hub or another Docker registry
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push images to Docker Hub
      - name: Push Image 1
        run: docker push myapp1

      - name: Push Image 2
        run: docker push myapp2

      - name: Push Image 3
        run: docker push myapp3
